import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { ClsService } from 'nestjs-cls';
import { Model, Types } from 'mongoose';
import { ScopedRepository } from '../scoped-repository';
import { Document, DocumentDocument, DocumentStatus } from '../models/document.schema';

@Injectable()
export class DocumentsRepository extends ScopedRepository<Document> {
  constructor(@InjectModel(Document.name) model: Model<Document>, cls: ClsService) {
    super(model, cls);
  }

  findByFolder(folderId: Types.ObjectId): Promise<DocumentDocument[]> {
    return this.find({ folderId }) as unknown as Promise<DocumentDocument[]>;
  }

  /**
   * `id` is optional and pre-generated by the caller uploading the first
   * version, so the Document and its DocumentVersion can cross-reference
   * each other's ids without an ordering hazard (see
   * DocumentVersionsRepository.createVersion for the matching id parameter).
   */
  createDocument(doc: {
    id?: Types.ObjectId;
    folderId: Types.ObjectId;
    name: string;
    latestVersionId: Types.ObjectId;
    createdBy: Types.ObjectId;
  }): Promise<DocumentDocument> {
    const { id, ...rest } = doc;
    const toInsert = id ? { ...rest, _id: id, status: 'queued' as const } : { ...rest, status: 'queued' as const };
    return this.model.create({ ...toInsert, ...this.scope() }) as unknown as Promise<DocumentDocument>;
  }

  /** A new version resets status to queued — the ingestion pipeline re-processes the new latest version (PRD §8). */
  async setLatestVersion(id: Types.ObjectId, latestVersionId: Types.ObjectId): Promise<void> {
    await this.updateOne({ _id: id }, { $set: { latestVersionId, status: 'queued' } });
  }

  async setStatus(id: Types.ObjectId, status: DocumentStatus): Promise<void> {
    await this.updateOne({ _id: id }, { $set: { status } });
  }

  async renameDocument(id: Types.ObjectId, name: string): Promise<DocumentDocument | null> {
    await this.updateOne({ _id: id }, { $set: { name } });
    return this.findById(id) as unknown as Promise<DocumentDocument | null>;
  }

  async moveDocument(id: Types.ObjectId, folderId: Types.ObjectId): Promise<DocumentDocument | null> {
    await this.updateOne({ _id: id }, { $set: { folderId } });
    return this.findById(id) as unknown as Promise<DocumentDocument | null>;
  }

  /** Stamped on each download-link issuance — best-effort visibility into "last opened", not a security- or correctness-critical write. */
  async touchLastOpened(id: Types.ObjectId): Promise<void> {
    await this.updateOne({ _id: id }, { $set: { lastOpenedAt: new Date() } });
  }
}
