import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { ClsService } from 'nestjs-cls';
import { Model, Types } from 'mongoose';
import { ScopedRepository } from '../scoped-repository';
import { DocumentVersion, DocumentVersionDocument } from '../models/document-version.schema';

@Injectable()
export class DocumentVersionsRepository extends ScopedRepository<DocumentVersion> {
  constructor(@InjectModel(DocumentVersion.name) model: Model<DocumentVersion>, cls: ClsService) {
    super(model, cls);
  }

  findByDocument(documentId: Types.ObjectId): Promise<DocumentVersionDocument[]> {
    return this.find({ documentId }) as unknown as Promise<DocumentVersionDocument[]>;
  }

  /** Highest versionNumber recorded for a document so far, or 0 if it has none yet. */
  async latestVersionNumber(documentId: Types.ObjectId): Promise<number> {
    const [top] = (await this.find({ documentId }).sort({ versionNumber: -1 }).limit(1)) as DocumentVersionDocument[];
    return top?.versionNumber ?? 0;
  }

  /**
   * `id` is optional and pre-generated by the caller when it must build the
   * storage key (ADR-0006) — and write the bytes — *before* this Mongo
   * record can exist, so a crash between the two never leaves a
   * DocumentVersion pointing at bytes that were never durably stored.
   */
  createVersion(doc: {
    id?: Types.ObjectId;
    documentId: Types.ObjectId;
    versionNumber: number;
    storageKey: string;
    originalFilename: string;
    mimeType: string;
    sizeBytes: number;
    contentHashSha256: string;
    uploadedBy: Types.ObjectId;
  }): Promise<DocumentVersionDocument> {
    const { id, ...rest } = doc;
    const toInsert = id ? { ...rest, _id: id } : rest;
    return this.model.create({ ...toInsert, ...this.scope() }) as unknown as Promise<DocumentVersionDocument>;
  }

  /** Sum of every retained version's size for the tenant — version history counts against quota (PRD §4/§8). */
  async sumSizeForTenant(): Promise<number> {
    const [result] = await this.aggregate<{ total: number }>([{ $group: { _id: null, total: { $sum: '$sizeBytes' } } }]);
    return result?.total ?? 0;
  }
}
